require:
  - rubocop-minitest
  - rubocop-rails

inherit_gem:
    rubocop-shopify: rubocop.yml

Style/FrozenStringLiteralComment:
  Enabled: true
    #  SafeAutoCorrect: false

Minitest/MultipleAssertions:
  Enabled: false


AllCops:
  NewCops: enable

